spring:
  profiles:
    active: local
---
spring:
   config:
     activate:
       on-profile: local
   jpa:
     hibernate:
       ddl-auto: create
     properties:
       hibernate:
         format_sql: true
         dialect: org.hibernate.dialect.H2Dialect
     show-sql: true
   datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:connectable
     username: sa
     password:
jwt:
   secret: uacc-to-the-moon
   expire-time: 14400000
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
kas:
  settings:
    enable-global-fee-payer: false
    account-pool-krn: krn:1001:wallet:664d1c4f-76cc-4664-84cd-f93bd28e3256:account-pool:default
    account-pool-address: "0xEa06ee0577795e39A0465b46d509168ff6302973"
    user-fee-payer-krn: krn:1001:wallet:664d1c4f-76cc-4664-84cd-f93bd28e3256:feepayer-pool:default
    user-fee-payer-address: "0xDFAD470f307CC3C524A96Ea86442F012f1DEF4d6"
    access-key-id: KASKOOU7SCEQTOSZ2FV0E9UQ
    secret-access-key: t-gAxJ_10sf7iqvo7qKxRIY6qUsyXMksMS6y0iY7
    chain-id: 1001
---
spring:
  config:
    activate:
      on-profile: dev
    import: 'aws-parameterstore:'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: connectable
jwt:
  secret: uacc-to-the-moon
  expire-time: 14400000
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
kas:
  settings:
    enable-global-fee-payer: false
    chain-id: 8217
    account-pool-krn: ${kas.account_pool_krn}
    account-pool-address: ${kas.account_pool_address}
    user-fee-payer-krn: ${kas.user_fee_payer_krn}
    user-fee-payer-address: ${kas.user_fee_payer_address}
    access-key-id: ${kas.access_key_id}
    secret-access-key: ${kas.secret_access_key}
